/*
THIS FILE IS UNRELATED TO THE PROJECT ITSELF IT'S FOR MY OWN PURPOSE
TO BE USED FOR ABSTRACTION LATER ON IF I CONTINUE TO WORK ON THIS
PROJECT
*/

abstract class UIBuilder {
  //TO-DO: TO BE USED LATER WHENEVER NEEDED
}
